<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="perfil">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="usuario" type="xs:string" />
                <xs:element name="juego">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="partidas">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="partida">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="clase" type="xs:string" />
                                                    <xs:element name="jefe">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name="nombre"
                                                                    type="xs:string" />
                                                                <xs:element name="clase"
                                                                    type="xs:string" />
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                    <xs:element name="puntos" type="xs:string" />
                                                </xs:sequence>
                                                <xs:attribute name="id" type="xs:integer"
                                                    use="required" />
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="logros">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="logro" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="nombre" type="xs:string" />
                                                    <xs:element name="descripccion" type="xs:string" />
                                                </xs:sequence>
                                                <xs:attribute name="puntos" type="xs:integer"
                                                    use="required">
                                                    <xs:simpleType>
                                                        <xs:restriction base="xs:string">
                                                            <xs:enumeration value="10" />
                                                            <xs:enumeration value="15" />
                                                            <xs:enumeration value="25" />
                                                            <xs:enumeration value="5" />
                                                        </xs:restriction>
                                                    </xs:simpleType>
                                                </xs:attribute>
                                                <xs:attribute name="completado" use="required"
                                                    fixed="no" />
                                                <xs:attribute name="secreto" use="required">
                                                    <xs:simpleType>
                                                        <xs:restriction base="xs:string">
                                                            <xs:enumeration value="no" />
                                                            <xs:enumeration value="si" />
                                                        </xs:restriction>
                                                    </xs:simpleType>
                                                </xs:attribute>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="nombre" use="required" />
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>