<!ELEMENT perfil (usuario,juego)>
<!ELEMENT usuario (#PCDATA)>
<!ELEMENT juego (partidas,logros)>
<!ELEMENT partidas (partida)>
<!ATTLIST juego nombre CDATA #REQUIRED>
<!ELEMENT partida (clase,jefe,puntos)>
<!ATTLIST partida id NMTOKEN #REQUIRED>
<!ELEMENT clase (#PCDATA)>
<!ELEMENT jefe (nombre,clase)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT puntos (#PCDATA)>
<!ELEMENT logros (logro+)>
<!ELEMENT logro (nombre,descripccion)>
<!ATTLIST logro puntos (10|15|25|5) #REQUIRED>
<!ATTLIST logro completado NMTOKEN #FIXED "no">
<!ATTLIST logro secreto (no|si) #REQUIRED>
<!ELEMENT descripccion (#PCDATA)>