<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<!-- Esquema de diseño plano o de uso de referencias -->

<!-- Comienzo del elemento perfil -->
    <xs:element name="perfil">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="usuario"/>
                <xs:element ref="juego"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <!-- Comienzo del elemento juego -->
    <xs:element name="juego">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="partidas"/>
                <xs:element ref="logros"/>
            </xs:sequence>
            <xs:attribute ref="nombre"/>
        </xs:complexType>
    </xs:element>

    <!-- Comienzo del elemento partidas -->
    <xs:element name="partidas">
        <xs:complexType>
            <xs:sequence>
                <!-- maxOccurs="unbounded" porque puede haber partidas infinitas -->
                <xs:element ref="partida" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <!-- Comienzo del elemento partida -->
    <xs:element name="partida">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="clase"/>
                <xs:element ref="jefe"/>
                <xs:element ref="puntos"/>
            </xs:sequence>
            <xs:attribute ref="id"/>
        </xs:complexType>
    </xs:element>

    <!-- Comienzo del elemento jefe -->
    <xs:element name="jefe">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="nombre"/>
                <xs:element ref="clase"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <!-- Comienzo del elemento logros -->
    <xs:element name="logros">
        <xs:complexType>
            <xs:sequence>
                <!-- maxOccurs="unbounded" porque puede haber logros infinitos -->
                <xs:element ref="logro" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <!-- Comienzo del elemento logro -->
    <xs:element name="logro">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="nombre"/>
                <xs:element ref="descripcion"/>
            </xs:sequence>
            <xs:attribute ref="puntos"/>
            <xs:attribute ref="completado"/>
            <xs:attribute ref="secreto"/>
        </xs:complexType>
    </xs:element>

    <!-- Elementos simples -->
    <xs:element name="usuario" type="xs:string"/>
    <xs:element name="clase" type="xs:string"/>
    <xs:element name="nombre" type="xs:string"/>
    <xs:element name="puntos" type="xs:integer"/>
    <xs:element name="descripcion" type="xs:string"/>
    <xs:element name="completado" type="xs:string"/>
    <xs:element name="secreto" type="xs:string"/>
    <xs:element name="id" type="xs:integer"/>

    <xs:attribute name="nombre" type="xs:string"/>
    <xs:attribute name="id" type="xs:integer"/>

    <xs:attribute name="puntos">
             <xs:simpleType>
                    <xs:restriction base="xs:integer">
                        <xs:enumeration value="5"/>
                        <xs:enumeration value="10"/>
                        <xs:enumeration value="15"/>
                        <xs:enumeration value="25"/>
                    </xs:restriction>
                </xs:simpleType>
    </xs:attribute>

    <xs:attribute name="completado">
             <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="no"/>
                        <xs:enumeration value="si"/>
                    </xs:restriction>
                </xs:simpleType>
    </xs:attribute>

    <xs:attribute name="secreto">
             <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="no"/>
                        <xs:enumeration value="si"/>
                    </xs:restriction>
                </xs:simpleType>
    </xs:attribute>
</xs:schema>